name: CBAE action

on: 
  push:
  workflow_dispatch:

jobs:
  cbom-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CBOM Analysis
        uses: Namokar100/cbae-action@v1.0.8
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commands-to-install-build-tools: |
            sudo apt-get update
            sudo apt-get install -y build-essential flex bison libssl-dev libelf-dev bc kmod cpio python3
          build-command: |
            make defconfig
            make -j$(nproc) bzImage